spring.application.name=B2LShoes

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.location=uploads/
logging.level.com.example=DEBUG


spring.datasource.url=jdbc:mysql://localhost:3306/lumitag_shop?useUnicode=true&characterEncoding=utf-8&characterSetResults=utf8mb4&connectionCollation=utf8mb4_unicode_ci&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=webshoes
spring.datasource.password=webshoes
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Đặt tên đăng nhập cố định
spring.security.user.name=admin

# Đặt mật khẩu cố định (bạn có thể đổi 'password123' thành bất cứ thứ gì)
spring.security.user.password=password123