spring.application.name=B2LShoes

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
logging.level.com.example=DEBUG


spring.datasource.url=jdbc:mysql://localhost:3306/b2lshoes?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=webshoes
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# C?u h\uFFFDnh Server Mail (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=23520842@gm.uit.edu.vn
spring.mail.password=s o g b c n b h s y c u m d s f
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true


spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=60000
spring.mail.properties.mail.smtp.writetimeout=60000

vnpay.tmnCode=WE6TLQIZ
vnpay.hashSecret=Q6ATLT6CLX9UAW3BMAQXSJA9YUWCY3SB
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/customer/payment/vnpay-callback

# C\u1EA5u h\u00ECnh file ng\u00F4n ng\u1EEF
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.cache-duration=3600